language: rust

matrix:
  include:
    # Linux
    - rust: stable
      os: linux
    - rust: beta
      os: linux
    - rust: nightly
      os: linux
    # OS X
    - rust: stable
      os: osx
    - rust: beta
      os: osx
    - rust: nightly
      os: osx
    # Windows MSVC
    - rust: stable-x86_64-pc-windows-msvc
      os: windows
    - rust: beta-x86_64-pc-windows-msvc
      os: windows
    - rust: nightly-x86_64-pc-windows-msvc
      os: windows
    # Windows GNU
    - rust: stable-x86_64-pc-windows-gnu
      os: windows
    - rust: beta-x86_64-pc-windows-gnu
      os: windows
    - rust: nightly-x86_64-pc-windows-gnu
      os: windows

cache: cargo

script:
  - cargo test
  - cargo test --release
